version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  target-branch: "development"
  schedule:
    interval: weekly
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "development"
  schedule:
    interval: "weekly"
