ARG BUILDER_IMAGE="hexpm/elixir:1.13.0-erlang-24.3.3-debian-bullseye-20210902-slim"
ARG RUNNER_IMAGE="debian:bullseye-20210902-slim"

FROM ${BUILDER_IMAGE} as builder

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential dialog apt-utils gpg-agent \
    apt-transport-https software-properties-common git curl postgresql-client inotify-tools && \
    curl -fsSL https://deb.nodesource.com/setup_15.x |bash - && \
    apt-get update && apt-get install -y nodejs python && \
    mix local.hex --force && \
    mix archive.install hex phx_new 1.5.9 --force && \
    mix local.rebar --force && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
WORKDIR /app
COPY . .
# COPY entrypoint.dev.sh /usr/bin/entrypoint.dev.sh
# RUN chmod +x /usr/bin/entrypoint.dev.sh
# ENTRYPOINT ["/usr/bin/entrypoint.dev.sh"]
EXPOSE 4001
EXPOSE 4000
CMD /bin/sh -c "while sleep 1000; do :; done"